server:
  port: 14000

spring:
  redis:
    password: skf123!@!
    host: 192.168.112.130

  datasource:
    username: root
    password: root
    url: jdbc:mysql://121.196.198.8:3306/gmall_order?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  main:
    allow-bean-definition-overriding: true


service:
  order:
    timeout: 1800

