server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true


auth-urls:
  auth:
    - /submitOrder/**
    - /api/order/**   #/api/order/orderlist/inner
  login-url: http://passport.gmall.com/login.html