server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

#        - id: service-item
#          uri: lb://service-item
#          predicates:
#            - Path=/api/item/**

        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
