server:
  port: 8000


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://121.196.198.8:3306/gmall_product?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.112.130
    port: 6379
    password: skf123!@!
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

service:
  minio:
    endpoint: http://192.168.112.130:9000
    accessKey: mall
    secretKey: mall123456
    bucketName: mall0624
  bloom:
    config:
      sku:
        bloom-name: "sku-bloom"
        expected-insertions: 1000000
        false-probability: 0.0001
        sku-rebild-cron: 0 0 3 */3 * ?
      spu:
        bloom-name: "spu-bloom"
        expected-insertions: 1000000
        false-probability: 0.0001
        sku-rebild-cron: 0 0 3 */3 * ?
#  thread-pool:
#    core-pool-size: 8
#    maximum-pool-size: 32
#    keep-alive-time: 60 # 默认为秒
#    name: "product-thread-pool-"




logging:
  level:
    root: INFO  #默认的日志等级   从小到大 TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF







